services:
  backend:
    build: ./backend
    ports: 
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/backend

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/frontend
      - timetable:/usr/src/frontend/timetable

volumes:
  timetable: